version: "3"

services:
  generate:
    build: ./
    command: python -m scripts.generate -c /configs/docker.json
    volumes:
      - ./models:/models
      - ./configs:/configs
      - ./core:/app/core
      - ./scripts:/app/scripts
      - ./outputs:/outputs
    environment:
      - DEVICE=cuda

  train:
    build: ./
    command: python -m scripts.train -c /configs/models/vqgan_custom_docker.json
    volumes:
      - ./models:/models
      - ./configs:/configs
      - ./core:/app/core
      - ./scripts:/app/scripts
      - ./outputs:/outputs
    environment:
      - DEVICE=cuda
